
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvkmvqmrnqpybynqumca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2a212cW1ybnFweWJ5bnF1bWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Nzk3NDAsImV4cCI6MjA1NjM1NTc0MH0.S-hZYYz4INcns4MPr8fe9w6RyCNKrK7imBBQkC_Ef_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
